#!/usr/bin/with-contenv bash

# wait for X to be running
while true; do
  if xset q &>/dev/null; then
    break
  fi
  sleep .5
done

# set sane resolution before starting apps
if ! s6-setuidgid abc xrandr | grep -q "1024x768"; then
  s6-setuidgid abc xrandr --newmode "1024x768" 63.50  1024 1072 1176 1328  768 771 775 798 -hsync +vsync
  s6-setuidgid abc xrandr --addmode screen "1024x768"
  s6-setuidgid abc xrandr --output screen --mode "1024x768" --dpi 96
fi

# set xresources
if [ -f "${HOME}/.Xresources" ]; then
  xrdb "${HOME}/.Xresources"
else
  echo "Xcursor.theme: breeze" > "${HOME}/.Xresources"
  xrdb "${HOME}/.Xresources"
fi
chown abc:abc "${HOME}/.Xresources"
chmod 777 /tmp/selkies*

# run
cd $HOME
exec s6-setuidgid abc \
  /bin/bash /defaults/startwm.sh &
PID=$!
echo "$PID" > /de-pid
wait "$PID"
